name: GitHub Profile Summary Cards

on:
  schedule:
    - cron: '0 0 * * *'  # Каждый день в полночь
  push:
    branches: [ main, master ]
  workflow_dispatch:  # Запуск вручную

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Summary Cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: malexple
          THEME: tokyonight
          UTC_OFFSET: 3  # Москва
          AUTO_PUSH: true
          BRANCH_NAME: main